<?php


namespace app\models;
use yii\db\ActiveRecord

class ProductForm extends ActiveRecord
{
 public static function tableName()
 {
     return parent::tableName('products'); // TODO: Change the autogenerated stub
 }
}